### ISSUE TITLE
Add an utility to get the final HTTPS url

### ISSUE THREAD

**Issue by danielpre30** [aws/git-remote-codecommit#30]
I'm building a node library and wanted to install it in another project like:
`npm install git+codecommit://<My-library>`

but npm doesn't accept this URL and I got the error:
`Unsupported URL Type "codecommit:"`

I would like there would be a utility to get the final URL and I could install my library like:
`npm install git+https://(username):(password)@git-codecommit.(region).(website_domain)/v1/repos/(repository)`

**Comment by timblaktu** [comment]
@danielpre30 can you provide guidance on how this was completed? I don't see anything in the docs about a utility to help form a repo url for use with git-remote-codecommit, based on the standard https (or ssh) url. I apologize if I'm misinterpreted this issue, but what I've stated is what I'm looking for so I don't have to sed/awk/python my way through this manually. Thanks!
