### ISSUE TITLE
Trouble syncing from af-south-1 region

### ISSUE THREAD

**Issue by marcodafonseca** [aws/git-remote-codecommit#33]
Hi

I'm not sure where specifically the issue is lying, but all of AWS' documentation says that af-south-1 region is fully supported as far as CodeCommit is concerned, so I'm somewhat trying my luck here to be honest.

I have made sure that my AWS CLI, python, PIP and git-remote-codecommit are all completely up-to-date.

We use federation for our accounts which is why we use git-remote-codecommit as it has been super helpful to-date.

This is the command I'm trying to run:
```
git clone codecommit::af-south-1://AccountName@RepoName
```

This is the response I am getting:
>The following AWS Region is not available for use with AWS CodeCommit: af-south-1. For more information about CodeCommit's availability in AWS Regions, see the AWS CodeCommit User Guide. If an AWS Region is listed as supported but you receive this error, try updating your version of the AWS CLI or the AWS SDKs.

Is this an issue that needs to be fixed or is this something I'm doing wrong on my end?

af-south-1 region is enabled for the account in question as I've created the repository in said region.

Any help would be greatly appreciated.

Thanks in advance

**Comment by georgerushby** [comment]
Ran into the same problem and the cause was an older version of boto3

```
pip show boto3
Name: boto3
Version: 1.18.19
```

` pip install --upgrade boto3`

```
pip show boto3
Name: boto3
Version: 1.21.8
```

**Comment by marcodafonseca** [comment]
Thanks for the response, George. 

I did figure my issue out in the end. Should've posted it here. Sorry.

In the end my problem was caused by having two different versions of PHP installed and referenced in my PATH variables.
So, even though I would see v3.10 when running `php --version` the git-remote-codecommit was actually running through v2.8 which would cause the error message.
