### ISSUE TITLE
Failed to install git-remote-codecommit 1.0 in virtual env

### ISSUE THREAD

**Issue by samuelkarp** [aws/git-remote-codecommit#5]
Hello!

I've tried to install git-remote-codecommit using [pipx](https://pipxproject.github.io/pipx/) so that it has its own separate virtual env.  However, I get this error when I try to install:

```
$ pipx install git-remote-codecommit
    ERROR: Command errored out with exit status 1:
     command: /home/admin/.local/pipx/venvs/git-remote-codecommit/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cxeu1jzn/git-remote-codecommit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cxeu1jzn/git-remote-codecommit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-cxeu1jzn/git-remote-codecommit/pip-egg-info
         cwd: /tmp/pip-install-cxeu1jzn/git-remote-codecommit/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cxeu1jzn/git-remote-codecommit/setup.py", line 9, in <module>
        import six
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It looks like the dependency on `six` was introduced in [this commit](https://github.com/aws/git-remote-codecommit/commit/b781007b91f2a7b76d32be7f1a4269a96e16b114), but that dependency is not reflected in the [requirements.txt](https://github.com/aws/git-remote-codecommit/blob/1.0/requirements.txt).  I'm not a Python developer, so maybe I'm missing something, but I'd expect that dependency to be reflected there.

I was able to get around this by installing the 0.5 version of git-remote-codecommit.

Thanks!
Sam

**Comment by dytoto** [comment]
We removed six from our dependency list. This should work now.

**Comment by samuelkarp** [comment]
This seems to work now, thanks!
