### ISSUE TITLE
Pip install from CC repo

### ISSUE THREAD

**Issue by jabrennem** [aws/git-remote-codecommit#9]
Is there a way to use this to pip install a python package in a CodeCommit repository? 

pip install git-remote-codecommit
pip install git+codecommit::{region}://repo-name

**Comment by dytoto** [comment]
You should be able to clone your CodeCommit repository and then install the pip module. 

`git clone codecommit://<profile>@<python-package-in-repo>
python setup.py sdist
pip install --upgrade dist/<your-python-package>-*.tar.gz`

**Comment by jabrennem** [comment]
Thank you. I will try out the tuple idea. It would be a cool feature request for pip to add that scheme via the command line.

**Comment by frank-sorschak** [comment]
pip install git+https://{url_of_repo} worked for me with my git-codecommit repo
